apiVersion: apps/v1
kind: Deployment
metadata:
  name: malaria-classification-api-dpl
  labels:
    app: malaria-classification-api-dpl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: malaria-classification-api-dpl
  template:
    metadata:
      labels:
        app: malaria-classification-api-dpl
    spec:
      containers:
      - name: malaria-classification-api-dpl
        image: ghcr.io/dewildedaan/eindopdrachtmlops-mcts5:latest
        ports:
        - containerPort: 80
      restartPolicy: Always